---
- name: loop
  hosts: localhost
  ignore_errors: true
  #  gather_facts: true

  tasks:
         - shell: ansible-playbook ./winUpdateSecurity.yml -i somePATH/host.ini
           register: results
           until: "'\"found_update_count\": 0' in results.stdout" 
           retries: 10

         - shell: ansible-playbook ./winUpdateCritical.yml -i somePATH/host.ini
           register: results
           until: "'\"found_update_count\": 0' in results.stdout" 
           retries: 10

         - shell: ansible-playbook ./winUpdateRollups.yml -i somePATH/host.ini
           register: results
           until: "'\"found_update_count\": 0' in results.stdout" 
           retries: 10
